# Generated by Django 2.0.6 on 2018-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationrecord',
            name='status',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
