# Generated by Django 2.1.1 on 2018-09-20 18:20

from django.db import migrations, models
import tom_observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0002_dataproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproduct',
            name='url',
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='data',
            field=models.FileField(default=None, null=True, upload_to=tom_observations.models.data_product_path),
        ),
    ]
