# Generated by Django 2.1.1 on 2018-09-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0003_auto_20180920_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproduct',
            name='product_id',
            field=models.CharField(default='a', max_length=2000, unique=True),
            preserve_default=False,
        ),
    ]
