# Generated by Django 2.0.6 on 2018-09-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0004_dataproduct_product_id'),
        ('tom_observations', '0002_observationrecord_status'),
    ]

    operations = [
    ]
