# Generated by Django 2.0.6 on 2018-09-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0005_merge_20180921_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataproduct',
            options={'ordering': ('-created',)},
        ),
    ]
