# Generated by Django 2.1.1 on 2018-09-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0006_auto_20180921_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='group',
            field=models.ManyToManyField(to='tom_observations.DataProductGroup'),
        ),
    ]
