# Generated by Django 2.0.6 on 2018-09-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0007_auto_20180924_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataproductgroup',
            options={'ordering': ('-created',)},
        ),
    ]
