# Generated by Django 2.0.6 on 2018-10-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0008_auto_20180926_1707'),
        ('tom_observations', '0008_auto_20180925_2054'),
    ]

    operations = [
    ]
