# Generated by Django 2.0.6 on 2018-10-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0009_merge_20181003_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observationrecord',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='tag',
            field=models.TextField(blank=True, default=''),
        ),
    ]
