# Generated by Django 2.0.6 on 2018-10-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0010_auto_20181019_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='product_id',
            field=models.CharField(max_length=2000, null=True, unique=True),
        ),
    ]
