# Generated by Django 4.2.23 on 2025-09-14 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0012_auto_20210205_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(blank=True, max_length=20, null=True)),
                ('mpc_site_code', models.CharField(blank=True, max_length=3, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[('ground', 'Ground-based'), ('space', 'Space-based')], max_length=15)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('elevation', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-3000.0), django.core.validators.MaxValueValidator(5000.0)])),
                ('orbit', models.CharField(blank=True, choices=[('leo', 'Low-Earth Orbit'), ('l2', 'Lagrange Point 2')], max_length=20, null=True)),
                ('diameter', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)])),
                ('typical_seeing', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(15.0)])),
                ('detector_type', models.CharField(max_length=30)),
                ('info_url', models.URLField(blank=True, max_length=400, null=True)),
                ('api_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
