# Generated by Django 2.0.6 on 2018-10-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0012_auto_20181022_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=2000, unique=True),
            preserve_default=False,
        ),
    ]
