# Generated by Django 4.2.23 on 2025-09-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0013_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='orbit',
            field=models.CharField(blank=True, choices=[('leo', 'Low-Earth Orbit'), ('l2', 'Lagrange Point 2'), ('earth-trailing', 'Earth-trailing orbit'), ('geosync', 'Geosynchronous orbit'), ('polar', 'Polar orbit'), ('elliptical', 'Elliptical orbit')], max_length=20, null=True),
        ),
    ]
