# Generated by Django 2.0.6 on 2018-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0013_auto_20181022_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='product_id',
            field=models.CharField(max_length=2000, null=True, unique=True),
        ),
    ]
