# Generated by Django 2.0.6 on 2018-10-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0014_auto_20181023_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproduct',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
