# Generated by Django 4.2.23 on 2025-09-17 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0014_alter_facility_orbit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='mpc_site_code',
        ),
        migrations.AddField(
            model_name='facility',
            name='mpc_observatory_code',
            field=models.CharField(blank=True, help_text="<a href='https://minorplanetcenter.net/iau/lists/ObsCodesF.html'>MPC Observatory Code List</a>", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='api_url',
            field=models.URLField(blank=True, help_text='Root URL of the facilities API endpoints', null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='detector_type',
            field=models.CharField(choices=[('gammaray', 'Gammay-ray'), ('xray', 'X-ray'), ('uv', 'Ultraviolet'), ('optical', 'Optical'), ('nir', 'Near Infrared'), ('uvoir', 'UV/optical/NIR'), ('submm', 'Submillimeter'), ('microwave', 'Microwave'), ('radio', 'Radio'), ('gw', 'Gravitational Waves'), ('neutrino', 'Neutrinos'), ('cherenkov', 'Cherenkov radiation'), ('multiband', 'Multiple detectors')], help_text='Electromagnetic wavelength or messenger type detected', max_length=30),
        ),
        migrations.AlterField(
            model_name='facility',
            name='diameter',
            field=models.FloatField(blank=True, help_text='Diameter of primary detector in meters', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(600.0)]),
        ),
        migrations.AlterField(
            model_name='facility',
            name='elevation',
            field=models.FloatField(blank=True, help_text='Elevation in meters', null=True, validators=[django.core.validators.MinValueValidator(-3000.0), django.core.validators.MaxValueValidator(6000.0)]),
        ),
        migrations.AlterField(
            model_name='facility',
            name='info_url',
            field=models.URLField(blank=True, help_text='URL of website where more information about the facility can be found', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude in decimal degrees', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='facility',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude in decimal degrees', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='facility',
            name='orbit',
            field=models.CharField(blank=True, choices=[('leo', 'Low-Earth Orbit'), ('l2', 'Lagrange Point 2'), ('earth-trailing', 'Earth-trailing orbit'), ('geosync', 'Geosynchronous orbit'), ('polar', 'Polar orbit'), ('elliptical', 'Elliptical orbit')], help_text='Orbit regime of space-based facility', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='site_code',
            field=models.CharField(blank=True, help_text='Short-hand identifier for the facility', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='typical_seeing',
            field=models.FloatField(blank=True, help_text='Seeing in arcsec', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(15.0)]),
        ),
    ]
