# Generated by Django 4.2.26 on 2026-01-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0015_remove_facility_mpc_site_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
    ]
