# Generated by Django 4.1 on 2022-10-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_alerts', '0005_alertstreammessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertstreammessage',
            name='exchange_status',
            field=models.CharField(choices=[('published', 'Published'), ('ingested', 'Ingested')], help_text='Whether this message was sent or received.', max_length=10, verbose_name='Exchange Status'),
        ),
    ]
