# Generated by Django 4.1.6 on 2023-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_alerts', '0006_alter_alertstreammessage_exchange_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertstreammessage',
            name='message_id',
            field=models.CharField(help_text='An external message identifier that can be used to locate the message within the given topic.', max_length=50, null=True, verbose_name='Message ID'),
        ),
    ]
