# Generated by Django 2.0.6 on 2018-06-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.CharField(help_text='The identifier for this object, e.g. Kelt-16b.', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text="The name of this target e.g. Barnard's star.", max_length=100)),
                ('designation', models.CharField(default='', help_text='Designation of this target.', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time which this target was created in the TOM database.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The time which this target was changed in the TOM database.')),
                ('ra', models.FloatField(blank=True, help_text='Right Ascension, in degrees.', null=True)),
                ('dec', models.FloatField(blank=True, help_text='Declination, in degrees.', null=True)),
                ('epoch', models.FloatField(blank=True, help_text='Julain Years. Max 2100.', null=True)),
                ('pm_ra', models.FloatField(blank=True, help_text='Proper Motion: RA. Milliarsec/year.', null=True)),
                ('pm_dec', models.FloatField(blank=True, help_text='Proper Motion: Dec. Milliarsec/year.', null=True)),
                ('galactic_lng', models.FloatField(blank=True, help_text='Galactic Longitude in degrees.', null=True)),
                ('galactic_lat', models.FloatField(blank=True, help_text='Galactic Latitude in degrees.', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Parsecs.', null=True)),
                ('distance_err', models.FloatField(blank=True, help_text='Parsecs.', null=True)),
                ('mean_anomoly', models.FloatField(blank=True, help_text='Angle in degrees.', null=True)),
                ('arg_of_perihelion', models.FloatField(blank=True, help_text='Argument of Perhihelion. J2000. Degrees.', null=True)),
                ('lng_asc_node', models.FloatField(blank=True, help_text='Longitude of Ascending Node. J2000. Degrees.', null=True)),
                ('inclination', models.FloatField(blank=True, help_text='Inclination to the ecliptic. J2000. Degrees.', null=True)),
                ('mean_daily_motion', models.FloatField(blank=True, help_text='Degrees per day.', null=True)),
                ('semimajor_axis', models.FloatField(blank=True, help_text='In AU', null=True)),
                ('ephemeris_period', models.FloatField(blank=True, help_text='Days', null=True)),
                ('ephemeris_period_err', models.FloatField(blank=True, help_text='Days', null=True)),
                ('ephemeris_epoch', models.FloatField(blank=True, help_text='Days', null=True)),
                ('ephemeris_epoch_err', models.FloatField(blank=True, help_text='Days', null=True)),
            ],
        ),
    ]
