# Generated by Django 2.0.6 on 2018-06-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the target list.', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time which this target list was created in the TOM database.')),
            ],
        ),
        migrations.RenameField(
            model_name='target',
            old_name='id',
            new_name='identifier',
        ),
        migrations.RemoveField(
            model_name='target',
            name='mean_anomoly',
        ),
        migrations.AddField(
            model_name='target',
            name='mean_anomaly',
            field=models.FloatField(blank=True, help_text='Angle in degrees.', null=True, verbose_name='Mean Anomaly'),
        ),
        migrations.AlterField(
            model_name='target',
            name='arg_of_perihelion',
            field=models.FloatField(blank=True, help_text='Argument of Perhihelion. J2000. Degrees.', null=True, verbose_name='Argument of Perihelion'),
        ),
        migrations.AlterField(
            model_name='target',
            name='dec',
            field=models.FloatField(blank=True, help_text='Declination, in degrees.', null=True, verbose_name='Declination'),
        ),
        migrations.AlterField(
            model_name='target',
            name='distance',
            field=models.FloatField(blank=True, help_text='Parsecs.', null=True, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='target',
            name='distance_err',
            field=models.FloatField(blank=True, help_text='Parsecs.', null=True, verbose_name='Distance Error'),
        ),
        migrations.AlterField(
            model_name='target',
            name='ephemeris_epoch',
            field=models.FloatField(blank=True, help_text='Days', null=True, verbose_name='Ephemeris Epoch'),
        ),
        migrations.AlterField(
            model_name='target',
            name='ephemeris_epoch_err',
            field=models.FloatField(blank=True, help_text='Days', null=True, verbose_name='Ephemeris Epoch Error'),
        ),
        migrations.AlterField(
            model_name='target',
            name='ephemeris_period',
            field=models.FloatField(blank=True, help_text='Days', null=True, verbose_name='Ephemeris Period'),
        ),
        migrations.AlterField(
            model_name='target',
            name='ephemeris_period_err',
            field=models.FloatField(blank=True, help_text='Days', null=True, verbose_name='Ephemeris Period Error'),
        ),
        migrations.AlterField(
            model_name='target',
            name='epoch',
            field=models.FloatField(blank=True, help_text='Julian Years. Max 2100.', null=True, verbose_name='Epoch of Elements'),
        ),
        migrations.AlterField(
            model_name='target',
            name='galactic_lat',
            field=models.FloatField(blank=True, help_text='Galactic Latitude in degrees.', null=True, verbose_name='Galactic Latitude'),
        ),
        migrations.AlterField(
            model_name='target',
            name='galactic_lng',
            field=models.FloatField(blank=True, help_text='Galactic Longitude in degrees.', null=True, verbose_name='Galactic Longitude'),
        ),
        migrations.AlterField(
            model_name='target',
            name='inclination',
            field=models.FloatField(blank=True, help_text='Inclination to the ecliptic. J2000. Degrees.', null=True, verbose_name='Inclination to the ecliptic'),
        ),
        migrations.AlterField(
            model_name='target',
            name='lng_asc_node',
            field=models.FloatField(blank=True, help_text='Longitude of Ascending Node. J2000. Degrees.', null=True, verbose_name='Longitude of Ascending Node'),
        ),
        migrations.AlterField(
            model_name='target',
            name='mean_daily_motion',
            field=models.FloatField(blank=True, help_text='Degrees per day.', null=True, verbose_name='Mean Daily Motion'),
        ),
        migrations.AlterField(
            model_name='target',
            name='pm_dec',
            field=models.FloatField(blank=True, help_text='Proper Motion: Dec. Milliarsec/year.', null=True, verbose_name='Proper Motion (Declination)'),
        ),
        migrations.AlterField(
            model_name='target',
            name='pm_ra',
            field=models.FloatField(blank=True, help_text='Proper Motion: RA. Milliarsec/year.', null=True, verbose_name='Proper Motion (RA)'),
        ),
        migrations.AlterField(
            model_name='target',
            name='ra',
            field=models.FloatField(blank=True, help_text='Right Ascension, in degrees.', null=True, verbose_name='Right Ascension'),
        ),
        migrations.AlterField(
            model_name='target',
            name='semimajor_axis',
            field=models.FloatField(blank=True, help_text='In AU', null=True, verbose_name='Semimajor Axis'),
        ),
        migrations.AddField(
            model_name='targetlist',
            name='targets',
            field=models.ManyToManyField(to='tom_targets.Target'),
        ),
    ]
