# Generated by Django 2.0.6 on 2018-06-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='type',
            field=models.CharField(choices=[('SIDEREAL', 'Sidereal'), ('NON_SIDEREAL', 'Non Sidereal')], default='SIDEREAL', max_length=20),
            preserve_default=False,
        ),
    ]
