# Generated by Django 2.1 on 2018-09-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0002_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='target',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The time which this target was created in the TOM database.', verbose_name='Time Created'),
        ),
        migrations.AlterField(
            model_name='target',
            name='designation',
            field=models.CharField(default='', help_text='Designation of this target.', max_length=100, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='target',
            name='identifier',
            field=models.CharField(help_text='The identifier for this object, e.g. Kelt-16b.', max_length=100, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='target',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The time which this target was changed in the TOM database.', verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(default='', help_text="The name of this target e.g. Barnard's star.", max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.CharField(choices=[('SIDEREAL', 'Sidereal'), ('NON_SIDEREAL', 'Non-sidereal')], help_text='The type of this target.', max_length=100, verbose_name='Target Type'),
        ),
        migrations.AddField(
            model_name='targetextra',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target'),
        ),
    ]
