# Generated by Django 2.1.5 on 2019-01-18 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0002_auto_20190115_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='name',
        ),
        migrations.RemoveField(
            model_name='target',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='target',
            name='name3',
        ),
        migrations.AddField(
            model_name='targetname',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target'),
        ),
    ]
