# Generated by Django 2.1.1 on 2018-09-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0003_auto_20180905_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='designation',
        ),
    ]
