# Generated by Django 2.1.5 on 2019-02-01 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0003_auto_20190118_0340'),
        ('tom_targets', '0003_auto_20190201_0216'),
    ]

    operations = [
    ]
