# Generated by Django 2.1.5 on 2019-02-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0004_auto_20190123_2010'),
        ('tom_targets', '0004_merge_20190201_0219'),
    ]

    operations = [
    ]
