# Generated by Django 2.0.6 on 2018-09-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0005_auto_20180925_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='eccentricity',
            field=models.FloatField(blank=True, help_text='Eccentricity', null=True, verbose_name='Eccentricity'),
        ),
    ]
