# Generated by Django 2.1.5 on 2019-02-01 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0005_merge_20190201_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetname',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The time which this target name was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetname',
            name='primary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targetname',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
