# Generated by Django 2.0.6 on 2018-10-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0004_remove_target_designation'),
        ('tom_targets', '0006_target_eccentricity'),
    ]

    operations = [
    ]
