# Generated by Django 2.2.1 on 2019-05-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0006_auto_20190403_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='epoch_of_perihelion',
            field=models.FloatField(blank=True, help_text='Julian Date.', null=True, verbose_name='Epoch of Perihelion'),
        ),
    ]
