# Generated by Django 2.1.5 on 2019-02-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0006_auto_20190201_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetname',
            name='primary',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
