# Generated by Django 2.2.1 on 2019-05-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0007_auto_20190503_2318'),
        ('tom_targets', '0007_auto_20190515_0047'),
    ]

    operations = [
    ]
