# Generated by Django 2.1.5 on 2019-09-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0011_merge_20190731_1821'),
        ('tom_targets', '0007_auto_20190209_0314'),
    ]

    operations = [
    ]
