# Generated by Django 2.1.5 on 2019-09-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0012_merge_20190912_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='targetname',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
