# Generated by Django 2.2.1 on 2019-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0013_auto_20190912_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='name',
            field=models.CharField(default='', help_text="The name of this target e.g. Barnard's star.", max_length=100, verbose_name='Name'),
        ),
    ]
