# Generated by Django 2.2.1 on 2019-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0014_target_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(default='', help_text="The name of this target e.g. Barnard's star.", max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
