# Generated by Django 4.2.10 on 2024-04-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_observations', '0012_auto_20210205_1819'),
        ('tom_dataproducts', '0012_alter_reduceddatum_data_product_and_more'),
        ('tom_targets', '0020_alter_targetname_created_alter_targetname_modified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Target',
            new_name='BaseTarget',
        ),
        migrations.AlterModelOptions(
            name='basetarget',
            options={'permissions': (('view_target', 'View Target'), ('add_target', 'Add Target'), ('change_target', 'Change Target'), ('delete_target', 'Delete Target')), 'verbose_name': 'target'},
        ),
    ]
