# Generated by Django 4.2.18 on 2025-02-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0022_persistentshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetarget',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The time which this target was created in the TOM database.', verbose_name='Time Created'),
        ),
    ]
