# Generated by Django 4.2.13 on 2024-12-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0022_persistentshare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basetarget',
            options={'permissions': (('view_target', 'View Target'), ('add_target', 'Add Target'), ('share_target', 'Share Target'), ('change_target', 'Change Target'), ('delete_target', 'Delete Target')), 'verbose_name': 'target'},
        ),
    ]
