# Generated by Django 4.2.18 on 2025-02-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0023_alter_basetarget_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetarget',
            name='permissions',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', help_text='The acess level of this target, see the docs on public vs private targets.', max_length=100),
        ),
    ]
