# Generated by Django 4.2.18 on 2025-03-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0025_auto_20250206_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetarget',
            name='permissions',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', help_text='The access level of this target, see the docs on public vs private targets.', max_length=100),
        ),
    ]
