# Generated by Django 4.2.19 on 2025-07-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tom_targets", "0026_alter_basetarget_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetarget",
            name="epoch_of_elements",
            field=models.FloatField(
                blank=True,
                help_text="Modified Julian date.",
                null=True,
                verbose_name="Epoch of Elements",
            ),
        ),
        migrations.AlterField(
            model_name="basetarget",
            name="epoch_of_perihelion",
            field=models.FloatField(
                blank=True,
                help_text="Modified Julian Date.",
                null=True,
                verbose_name="Epoch of Perihelion",
            ),
        ),
    ]
