# Generated by Django 4.2.16 on 2025-08-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0027_alter_basetarget_epoch_of_elements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetarget',
            name='abs_mag',
            field=models.FloatField(blank=True, help_text='mag', null=True, verbose_name='Absolute Magnitude'),
        ),
        migrations.AddField(
            model_name='basetarget',
            name='slope',
            field=models.FloatField(blank=True, default=0.15, help_text='mag', null=True, verbose_name='Slope parameter'),
        ),
    ]
