# Generated by Django 4.2.24 on 2025-09-11 19:52

from django.db import migrations, models
import tom_targets.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0028_basetarget_abs_mag_basetarget_slope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetarget',
            name='permissions',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default=tom_targets.base_models.get_default_target_permission, help_text='The access level of this target, see the docs on public vs private targets.', max_length=100),
        ),
    ]
