# Generated by Django 4.2.25 on 2025-11-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0029_alter_basetarget_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetarget',
            name='slope',
        ),
        migrations.AddField(
            model_name='basetarget',
            name='_slope',
            field=models.FloatField(blank=True, help_text='mag', null=True, verbose_name='Slope parameter'),
        ),
    ]
