# Generated by Django 4.2.25 on 2025-11-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0029_alter_basetarget_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetarget',
            name='slope',
            field=models.FloatField(blank=True, help_text='mag', null=True, verbose_name='Slope parameter'),
        ),
    ]
