# Generated by Django 5.2.13 on 2026-07-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetarget',
            name='shared_by',
            field=models.CharField(blank=True, default='', help_text='Username', verbose_name='Shared by'),
        ),
        migrations.AddField(
            model_name='basetarget',
            name='shared_from',
            field=models.CharField(blank=True, default='', help_text='TOM name', verbose_name='Shared from'),
        ),
    ]
