# Generated by Django 4.2.27 on 2026-03-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_calendar', '0002_calendarevent_target_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='proposal',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='telescope',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
