# Generated by Django 4.2.27 on 2026-03-05 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_calendar', '0003_calendarevent_proposal_calendarevent_telescope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='tom_calendar.calendarevent')),
            ],
        ),
    ]
