# Generated by Django 4.2.27 on 2026-03-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_calendar', '0004_eventtodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='instrument',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
