# Generated by Django 2.1.4 on 2018-12-10 21:27

from django.db import migrations, models
import django.db.models.deletion
import tom_dataproducts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0001_initial'),
        ('tom_observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=2000, null=True, unique=True)),
                ('data', models.FileField(default=None, null=True, upload_to=tom_dataproducts.models.data_product_path)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField(blank=True, choices=[('light_curve', 'Light Curve'), ('fits_file', 'Fits File'), ('image_file', 'Image File')], default='')),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': ('modified',),
            },
        ),
        migrations.CreateModel(
            name='DataProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='group',
            field=models.ManyToManyField(to='tom_dataproducts.DataProductGroup'),
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='observation_record',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_observations.ObservationRecord'),
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target'),
        ),
    ]
