# Generated by Django 2.1.5 on 2019-02-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0004_auto_20190123_2010'),
        ('tom_dataproducts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('SPECTROSCOPY', 'Spectroscopy'), ('PHOTOMETRY', 'Photometry')], default='', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('label', models.CharField(default='', max_length=100)),
                ('error', models.FloatField(null=True)),
                ('data_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.DataProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ReducedDatumSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The original source reference for the datum', max_length=100, verbose_name='Datum Source')),
                ('location', models.CharField(help_text='URL or path to original target source reference', max_length=100, null=True, verbose_name='Datum Source Location')),
            ],
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.ReducedDatumSource'),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target'),
        ),
    ]
