# Generated by Django 2.1.4 on 2019-01-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0002_auto_20190130_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
