# Generated by Django 2.1.4 on 2019-02-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0003_auto_20190130_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reduceddatum',
            name='source',
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='source_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='source_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target'),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='value',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ReducedDatumSource',
        ),
    ]
