# Generated by Django 2.1.7 on 2019-06-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0003_merge_20190520_1645'),
        ('tom_dataproducts', '0004_merge_20190515_0914'),
    ]

    operations = [
    ]
