# Generated by Django 2.1.4 on 2019-02-06 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0004_auto_20190206_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='tag',
            field=models.CharField(blank=True, choices=[('photometry', 'Photometry'), ('fits_file', 'Fits File'), ('spectroscopy', 'Spectroscopy')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target'),
        ),
    ]
