# Generated by Django 2.1.4 on 2019-02-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0005_auto_20190206_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reduceddatum',
            name='error',
        ),
        migrations.RemoveField(
            model_name='reduceddatum',
            name='label',
        ),
    ]
