# Generated by Django 5.2.13 on 2026-04-27 23:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tom_dataproducts', '0011_reduceddatum_message'), ('tom_dataproducts', '0012_alter_reduceddatum_data_product_and_more'), ('tom_dataproducts', '0013_alter_reduceddatum_message'), ('tom_dataproducts', '0014_alter_reduceddatum_timestamp'), ('tom_dataproducts', '0015_remove_reduceddatum_message')]

    dependencies = [
        ('tom_dataproducts', '0010_manual_20210305_fix_spectroscopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='data_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.dataproduct'),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='source_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
