# Generated by Django 4.0.4 on 2022-05-03 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0019_auto_20210811_0018'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tom_dataproducts', '0010_manual_20210305_fix_spectroscopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduceddatum',
            name='error',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='facility',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='filter',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='mjd',
            field=models.FloatField(default=59702.56950572405),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='observer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='reduceddatum',
            unique_together={('target', 'data_type', 'mjd', 'value', 'filter')},
        ),
    ]
