# Generated by Django 4.2.1 on 2023-10-23 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0011_reduceddatum_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='data_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.dataproduct'),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='source_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
