# Generated by Django 4.2.18 on 2025-03-05 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0013_alter_reduceddatum_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
