# Generated by Django 5.2.12 on 2026-04-02 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_alerts', '0007_alter_alertstreammessage_message_id'),
        ('tom_dataproducts', '0014_alter_reduceddatum_timestamp'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduceddatum',
            name='instrument',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='telescope',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='value',
            field=models.JSONField(default=dict, verbose_name='extra data'),
        ),
        migrations.CreateModel(
            name='AstrometryReducedDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.JSONField(default=dict, verbose_name='extra data')),
                ('telescope', models.CharField(blank=True, default='', max_length=255)),
                ('instrument', models.CharField(blank=True, default='', max_length=255)),
                ('source_name', models.CharField(blank=True, default='', max_length=100)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('ra_error', models.FloatField(blank=True, default=None, null=True)),
                ('dec_error', models.FloatField(blank=True, default=None, null=True)),
                ('ra_error_units', models.CharField(blank=True, default='', max_length=32)),
                ('dec_error_units', models.CharField(blank=True, default='', max_length=32)),
                ('data_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.dataproduct')),
                ('message', models.ManyToManyField(blank=True, to='tom_alerts.alertstreammessage')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.basetarget')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'timestamp', 'telescope', 'instrument'), name='unique_astrometry')],
            },
        ),
        migrations.CreateModel(
            name='PhotometryReducedDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.JSONField(default=dict, verbose_name='extra data')),
                ('telescope', models.CharField(blank=True, default='', max_length=255)),
                ('instrument', models.CharField(blank=True, default='', max_length=255)),
                ('source_name', models.CharField(blank=True, default='', max_length=100)),
                ('discovery', models.BooleanField(default=False)),
                ('brightness', models.FloatField()),
                ('brightness_error', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('bandpass', models.CharField(max_length=32)),
                ('exposure_time', models.FloatField()),
                ('data_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.dataproduct')),
                ('message', models.ManyToManyField(blank=True, to='tom_alerts.alertstreammessage')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.basetarget')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'bandpass', 'timestamp'), name='unique_photometry')],
            },
        ),
        migrations.CreateModel(
            name='SpectroscopyReducedDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.JSONField(default=dict, verbose_name='extra data')),
                ('telescope', models.CharField(blank=True, default='', max_length=255)),
                ('instrument', models.CharField(blank=True, default='', max_length=255)),
                ('source_name', models.CharField(blank=True, default='', max_length=100)),
                ('setup', models.CharField(blank=True, default='', max_length=2000)),
                ('exposure_time', models.FloatField()),
                ('flux', models.TextField(blank=True, default='')),
                ('flux_unit', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('wavelength', models.TextField(blank=True, default='')),
                ('data_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.dataproduct')),
                ('message', models.ManyToManyField(blank=True, to='tom_alerts.alertstreammessage')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.basetarget')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'timestamp', 'telescope', 'instrument'), name='unique_spectroscopy')],
            },
        ),
    ]
