# Generated by Django 5.2.13 on 2026-04-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0014_alter_reduceddatum_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reduceddatum',
            name='message',
        ),
    ]
