# Generated by Django 5.2.12 on 2026-03-26 21:37
import uuid

from django.db import migrations, models

def populate_unique_keys(apps, schema_editor):
    """Assign a UUID to all existing rows so they don't conflict with the null-key constraint."""
    # Iterates over existing ReducedDatums without loading the entire set into memory.
    # Taken from example here: https://docs.djangoproject.com/en/6.0/ref/models/querysets/#bulk-update
    from itertools import islice
    ReducedDatum = apps.get_model('tom_dataproducts', 'ReducedDatum')

    batch_size = 1000
    ids_iter = ReducedDatum.objects.filter(unique_key__isnull=True).values_list('pk', flat=True).iterator()
    while ids := list(islice(ids_iter, batch_size)):
        batch = ReducedDatum.objects.filter(pk__in=ids)
        for datum in batch:
            datum.unique_key = str(uuid.uuid4())
        ReducedDatum.objects.bulk_update(batch, ['unique_key'], batch_size=batch_size)

class Migration(migrations.Migration):

    dependencies = [
        ('tom_alerts', '0007_alter_alertstreammessage_message_id'),
        ('tom_dataproducts', '0014_alter_reduceddatum_timestamp'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduceddatum',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_unique_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='reduceddatum',
            constraint=models.UniqueConstraint(condition=models.Q(('unique_key__isnull', False)), fields=('target', 'timestamp', 'unique_key'), name='unique_reduced_datum_with_key'),
        ),
        migrations.AddConstraint(
            model_name='reduceddatum',
            constraint=models.UniqueConstraint(condition=models.Q(('unique_key__isnull', True)), fields=('target', 'timestamp'), name='unique_reduced_datum_no_key'),
        ),
    ]
