# Generated by Django 5.2.13 on 2026-04-23 20:12

from django.db import migrations

BATCH_SIZE = 1000

BRIGHTNESS_FIELDS = ('brightness', 'magnitude', 'mag')
BRIGHTNESS_ERROR_FIELDS = ('brightness_error', 'error', 'magnitude_error', 'mag_error')
BANDPASS_FIELDS = ('bandpass', 'filter', 'band', 'f')


def _pop_first(d, keys, default=None):
    for key in keys:
        if key in d and d[key] is not None:
            return d[key]
    return default


def _run_batched(queryset, create_fn, TypedModel, ReducedDatum):
    to_create = []
    pks_to_delete = []

    for rd in queryset.iterator(chunk_size=BATCH_SIZE):
        instance = create_fn(rd)
        if instance is not None:
            to_create.append(instance)
            pks_to_delete.append(rd.pk)

        if len(to_create) >= BATCH_SIZE:
            TypedModel.objects.bulk_create(to_create, ignore_conflicts=True)
            ReducedDatum.objects.filter(pk__in=pks_to_delete).delete()
            to_create = []
            pks_to_delete = []

    if to_create:
        TypedModel.objects.bulk_create(to_create, ignore_conflicts=True)
        ReducedDatum.objects.filter(pk__in=pks_to_delete).delete()


def migrate_photometry(apps, schema_editor):
    ReducedDatum = apps.get_model('tom_dataproducts', 'ReducedDatum')
    PhotometryReducedDatum = apps.get_model('tom_dataproducts', 'PhotometryReducedDatum')

    def build(rd):
        value = rd.value or {}
        return PhotometryReducedDatum(
            target_id=rd.target_id,
            data_product_id=rd.data_product_id,
            source_name=rd.source_name,
            source_location=rd.source_location,
            timestamp=rd.timestamp,
            telescope=rd.telescope or value.get('telescope', ''),
            instrument=rd.instrument or value.get('instrument', ''),
            brightness=_pop_first(value, BRIGHTNESS_FIELDS),
            brightness_error=_pop_first(value, BRIGHTNESS_ERROR_FIELDS),
            limit=value.get('limit'),
            unit=value.get('unit', ''),
            bandpass=_pop_first(value, BANDPASS_FIELDS, default=''),
        )

    _run_batched(
        ReducedDatum.objects.filter(data_type='photometry'),
        build, PhotometryReducedDatum, ReducedDatum,
    )


def migrate_spectroscopy(apps, _schema_editor):
    ReducedDatum = apps.get_model('tom_dataproducts', 'ReducedDatum')
    SpectroscopyReducedDatum = apps.get_model('tom_dataproducts', 'SpectroscopyReducedDatum')

    def build(rd):
        value = rd.value or {}

        flux = value.get('flux', [])
        wavelength = value.get('wavelength', [])
        error = value.get('error', value.get('flux_error', []))

        return SpectroscopyReducedDatum(
            target_id=rd.target_id,
            data_product_id=rd.data_product_id,
            source_name=rd.source_name,
            source_location=rd.source_location,
            timestamp=rd.timestamp,
            telescope=rd.telescope or value.get('telescope', ''),
            instrument=rd.instrument or value.get('instrument', ''),
            flux=flux if isinstance(flux, list) else [],
            wavelength=wavelength if isinstance(wavelength, list) else [],
            error=error if isinstance(error, list) else [],
            flux_unit=value.get('flux_units', value.get('flux_unit', '')),
        )

    _run_batched(
        ReducedDatum.objects.filter(data_type='spectroscopy'),
        build, SpectroscopyReducedDatum, ReducedDatum,
    )


def migrate_astrometry(apps, schema_editor):
    ReducedDatum = apps.get_model('tom_dataproducts', 'ReducedDatum')
    AstrometryReducedDatum = apps.get_model('tom_dataproducts', 'AstrometryReducedDatum')

    def build(rd):
        value = rd.value or {}
        return AstrometryReducedDatum(
            target_id=rd.target_id,
            data_product_id=rd.data_product_id,
            source_name=rd.source_name,
            source_location=rd.source_location,
            timestamp=rd.timestamp,
            telescope=rd.telescope or value.get('telescope', ''),
            instrument=rd.instrument or value.get('instrument', ''),
            ra=value.get('ra'),
            dec=value.get('dec'),
            ra_error=value.get('ra_error'),
            dec_error=value.get('dec_error'),
            ra_error_units=value.get('ra_error_units', ''),
            dec_error_units=value.get('dec_error_units', ''),
        )

    _run_batched(
        ReducedDatum.objects.filter(data_type='astrometry'),
        build, AstrometryReducedDatum, ReducedDatum,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0015_reduceddatum_instrument_reduceddatum_telescope_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_photometry, migrations.RunPython.noop),
        migrations.RunPython(migrate_spectroscopy, migrations.RunPython.noop),
        migrations.RunPython(migrate_astrometry, migrations.RunPython.noop),
    ]
