# Generated by Django 5.2.14 on 2026-07-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0016_reduceddatum_instrument_reduceddatum_telescope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectroscopyreduceddatum',
            name='wavelength_unit',
            field=models.TextField(blank=True, default=''),
        ),
    ]
