# Generated by Django 5.2.16 on 2026-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0017_spectroscopyreduceddatum_wavelength_unit'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='astrometryreduceddatum',
            name='unique_astrometry',
        ),
        migrations.RemoveConstraint(
            model_name='photometryreduceddatum',
            name='unique_photometry',
        ),
        migrations.RemoveConstraint(
            model_name='spectroscopyreduceddatum',
            name='unique_spectroscopy',
        ),
        migrations.AddField(
            model_name='astrometryreduceddatum',
            name='reduction_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='photometryreduceddatum',
            name='reduction_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='reduction_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='spectroscopyreduceddatum',
            name='reduction_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='astrometryreduceddatum',
            constraint=models.UniqueConstraint(fields=('target', 'timestamp', 'telescope', 'instrument', 'ra', 'dec', 'reduction_version'), name='unique_astrometry', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='photometryreduceddatum',
            constraint=models.UniqueConstraint(fields=('target', 'bandpass', 'timestamp', 'limit', 'brightness', 'instrument', 'reduction_version'), name='unique_photometry', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='spectroscopyreduceddatum',
            constraint=models.UniqueConstraint(fields=('target', 'timestamp', 'telescope', 'instrument', 'flux', 'reduction_version'), name='unique_spectroscopy', nulls_distinct=False),
        ),
    ]
