# Generated by Django 5.2.16 on 2026-08-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0017_spectroscopyreduceddatum_wavelength_unit'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='astrometryreduceddatum',
            name='unique_astrometry',
        ),
        migrations.RemoveConstraint(
            model_name='photometryreduceddatum',
            name='unique_photometry',
        ),
        migrations.RemoveConstraint(
            model_name='spectroscopyreduceddatum',
            name='unique_spectroscopy',
        ),
        migrations.AddConstraint(
            model_name='astrometryreduceddatum',
            constraint=models.UniqueConstraint(fields=('target', 'timestamp', 'telescope', 'instrument', 'ra', 'dec'), name='unique_astrometry', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='photometryreduceddatum',
            constraint=models.UniqueConstraint(fields=('target', 'bandpass', 'timestamp', 'limit', 'brightness', 'instrument'), name='unique_photometry', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='spectroscopyreduceddatum',
            constraint=models.UniqueConstraint(fields=('target', 'timestamp', 'telescope', 'instrument', 'flux'), name='unique_spectroscopy', nulls_distinct=False),
        ),
    ]
