# Generated by Django 5.2.16 on 2026-07-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0017_spectroscopyreduceddatum_wavelength_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='astrometryreduceddatum',
            name='unique_astrometry',
        ),
        migrations.RemoveConstraint(
            model_name='photometryreduceddatum',
            name='unique_photometry',
        ),
        migrations.RemoveConstraint(
            model_name='spectroscopyreduceddatum',
            name='unique_spectroscopy',
        ),
    ]
