# Generated by Django 5.2.17 on 2026-08-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0018_remove_astrometryreduceddatum_unique_astrometry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astrometryreduceddatum',
            options={'get_latest_by': ('timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='photometryreduceddatum',
            options={'get_latest_by': ('timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='spectroscopyreduceddatum',
            options={'get_latest_by': ('timestamp',)},
        ),
    ]
