# Generated by Django 5.2.13 on 2026-09-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0019_alter_astrometryreduceddatum_options_and_more'),
        ('tom_targets', '0031_basetarget_shared_by_basetarget_shared_from'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='astrometryreduceddatum',
            name='unique_astrometry',
        ),
        migrations.RemoveConstraint(
            model_name='photometryreduceddatum',
            name='unique_photometry',
        ),
        migrations.RemoveConstraint(
            model_name='spectroscopyreduceddatum',
            name='unique_spectroscopy',
        ),
        migrations.AddConstraint(
            model_name='astrometryreduceddatum',
            constraint=models.UniqueConstraint(fields=('target', 'timestamp', 'telescope', 'instrument', 'ra', 'dec', 'reduction_version'), name='unique_astrometry'),
        ),
        migrations.AddConstraint(
            model_name='photometryreduceddatum',
            constraint=models.UniqueConstraint(fields=('target', 'bandpass', 'timestamp', 'brightness', 'instrument', 'reduction_version'), name='unique_photometry_brightness'),
        ),
        migrations.AddConstraint(
            model_name='photometryreduceddatum',
            constraint=models.UniqueConstraint(fields=('target', 'bandpass', 'timestamp', 'limit', 'instrument', 'reduction_version'), name='unique_photometry_limit'),
        ),
        migrations.AddConstraint(
            model_name='spectroscopyreduceddatum',
            constraint=models.UniqueConstraint(fields=('target', 'timestamp', 'telescope', 'instrument', 'flux', 'reduction_version'), name='unique_spectroscopy'),
        ),
    ]
