# Generated by Django 5.2.17 on 2026-10-08 23:01

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0020_remove_astrometryreduceddatum_unique_astrometry_and_more'),
        ('tom_targets', '0031_basetarget_shared_by_basetarget_shared_from'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='spectroscopyreduceddatum',
            name='unique_spectroscopy',
        ),
        migrations.AddConstraint(
            model_name='spectroscopyreduceddatum',
            constraint=models.UniqueConstraint(models.F('target'), models.F('timestamp'), models.F('telescope'), models.F('instrument'), django.db.models.functions.text.MD5(django.db.models.functions.comparison.Cast('flux', output_field=models.TextField())), models.F('reduction_version'), name='unique_spectroscopy'),
        ),
    ]
