# Generated by Django 4.0.4 on 2023-04-03 13:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bhtom_observations', '0012_auto_20210205_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('facilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None)),
                ('parameters', models.JSONField(blank=True, default='')),
                ('active_from', models.DateField()),
                ('active_to', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=2048, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-active_to', '-active_from'),
            },
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(check=models.Q(('active_to__gt', django.db.models.expressions.F('active_from'))), name='check_active_dates'),
        ),
    ]
