# Generated by Django 4.0.4 on 2023-04-03 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_observations', '0013_proposal_proposal_check_active_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='facilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=200), blank=True, default=[], size=None),
        ),
    ]
