# Generated by Django 5.2.12 on 2026-03-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_common', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_dek',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
