# Generated by Django 5.2.12 on 2026-03-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_common', '0003_profile_encrypted_dek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
