# Generated by Django 5.2.16 on 2026-08-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_common', '0004_delete_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
