# Generated by Django 5.2.11 on 2026-03-05 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataservices', '0001_initial'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_obs', models.IntegerField(blank=True, help_text='Number of observations', null=True)),
                ('neo_score', models.IntegerField(blank=True, help_text='NEO digest score (0..100)', null=True)),
                ('neo1km_score', models.IntegerField(blank=True, help_text='NEO >1km digest score (0..100)', null=True)),
                ('pha_score', models.IntegerField(blank=True, help_text='PHA digest score (0..100)', null=True)),
                ('ieo_score', models.IntegerField(blank=True, help_text='IEO digest score (0..100)', null=True)),
                ('geocentric_score', models.IntegerField(blank=True, help_text='Geocentric digest score (0..100)', null=True)),
                ('impact_rating', models.IntegerField(blank=True, choices=[(0, 'Negligible'), (1, 'Small'), (2, 'Modest'), (3, 'Moderate'), (4, 'Elevated')], help_text='Impact rating (0=negligible, 1=small, 2=modest, 3=moderate, 4=elevated)', null=True)),
                ('ca_dist', models.FloatField(blank=True, help_text='Close approach distance (lunar distances)', null=True)),
                ('arc', models.FloatField(blank=True, help_text='Arc length (days)', null=True)),
                ('rms', models.FloatField(blank=True, help_text='RMS of the residuals to the orbit fit (arcsec)', null=True)),
                ('uncertainty', models.FloatField(blank=True, help_text='1-sigma plane-of-sky positional uncertainty (arcmin)', null=True)),
                ('uncertainty_p1', models.FloatField(blank=True, help_text='1-sigma plane-of-sky positional uncertainty at +1 day (arcmin)', null=True)),
                ('last_run', models.DateTimeField(blank=True, help_text='Last time the data was updated from Scout', null=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scout_detail', to='tom_targets.basetarget')),
            ],
        ),
    ]
