# Generated by Django 4.0.4 on 2022-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0019_auto_20210811_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetname',
            name='source_name',
            field=models.CharField(choices=[('Gaia', 'Gaia name'), ('ZTF', 'ZTF name'), ('CPCS', 'CPCS name'), ('AAVSO', 'AAVSO name'), ('TNS', 'TNS name'), ('ASASSN', 'ASASSN name'), ('ANTARES', 'ANTARES name'), ('GAIA_DR2', 'GAIA_DR2 name'), ('ZTF_DR8', 'ZTF_DR8 name')], default='', max_length=100, verbose_name='Source Name'),
            preserve_default=False,
        ),
    ]
