# Generated by Django 4.0.4 on 2022-09-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0020_targetname_source_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targetname',
            unique_together={('source_name', 'target')},
        ),
    ]
