# Generated by Django 4.0.4 on 2022-10-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0022_alter_targetname_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetname',
            name='source_name',
            field=models.CharField(choices=[('GAIA', 'GAIA name'), ('ZTF', 'ZTF name'), ('CPCS', 'CPCS name'), ('AAVSO', 'AAVSO name'), ('TNS', 'TNS name'), ('ASASSN', 'ASASSN name'), ('ANTARES', 'ANTARES name'), ('GAIA_DR2', 'GAIA_DR2 name'), ('ZTF_DR8', 'ZTF_DR8 name'), ('GAIA_DR3', 'GAIA_DR3 name')], max_length=100, verbose_name='Source Name'),
        ),
    ]
