# Generated by Django 2.1.4 on 2019-01-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_dataproducts', '0001_initial'),
        ('tom_targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedDataGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target')),
            ],
        ),
        migrations.CreateModel(
            name='ReducedDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField()),
                ('value', models.FloatField()),
                ('label', models.TextField(null=True)),
                ('error', models.FloatField(null=True)),
                ('data_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.DataProduct')),
                ('group', models.ManyToManyField(to='tom_reduced_data.ReducedDataGrouping')),
            ],
        ),
    ]
