# Generated by Django 2.1.4 on 2019-01-15 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_reduced_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='data_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.DataProduct'),
        ),
    ]
