# Generated by Django 2.1.4 on 2019-01-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_reduced_data', '0002_auto_20190115_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='timestamp',
            field=models.TextField(db_index=True),
        ),
    ]
