# Generated by Django 2.1.4 on 2019-01-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0004_auto_20190123_2010'),
        ('tom_reduced_data', '0004_auto_20190121_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedDatumSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='The original source reference for the datum', max_length=100, unique=True, verbose_name='Datum Source')),
                ('location', models.TextField(help_text='URL or path to original target source reference', max_length=100, null=True, verbose_name='Datum Source Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='reduceddatagrouping',
            name='target',
        ),
        migrations.RemoveField(
            model_name='reduceddatum',
            name='group',
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='data_type',
            field=models.TextField(choices=[('SPECTROSCOPY', 'Spectroscopy'), ('PHOTOMETRY', 'Photometry')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReducedDataGrouping',
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tom_reduced_data.ReducedDatumSource'),
            preserve_default=False,
        ),
    ]
