# Generated by Django 2.1.4 on 2019-01-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_reduced_data', '0005_auto_20190123_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatumsource',
            name='name',
            field=models.TextField(help_text='The original source reference for the datum', max_length=100, verbose_name='Datum Source'),
        ),
    ]
