# Generated by Django 2.1.4 on 2019-01-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_reduced_data', '0006_auto_20190123_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='data_type',
            field=models.CharField(choices=[('SPECTROSCOPY', 'Spectroscopy'), ('PHOTOMETRY', 'Photometry')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='timestamp',
            field=models.FloatField(db_index=True),
        ),
    ]
