# Generated by Django 4.0.4 on 2022-05-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0011_reduceddatum_error_reduceddatum_extra_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='mjd',
            field=models.FloatField(default=59702.592867038125),
        ),
    ]
