# Generated by Django 4.0.4 on 2022-05-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0012_alter_reduceddatum_mjd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='facility',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='mjd',
            field=models.FloatField(default=59702.70042522912),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='observer',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
