# Generated by Django 4.0.4 on 2022-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0013_alter_reduceddatum_facility_alter_reduceddatum_mjd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='mjd',
            field=models.FloatField(default=59703.585760317015),
        ),
    ]
