# Generated by Django 4.0.4 on 2022-09-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0016_alter_reduceddatum_mjd'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduceddatum',
            name='value_unit',
            field=models.CharField(choices=[('MAG', 'mag'), ('JY', 'Jy'), ('ERG_S_CM2_ANGSTROM', 'erg/s/cm^2/Angstrom')], default='MAG', max_length=100),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='mjd',
            field=models.FloatField(default=59828.49549408801),
        ),
    ]
