# Generated by Django 4.0.4 on 2022-09-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0018_remove_reduceddatum_value_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='mjd',
            field=models.FloatField(default=59828.5693237258),
        ),
    ]
