# Generated by Django 4.0.4 on 2022-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0020_alter_reduceddatum_mjd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='mjd',
            field=models.FloatField(default=59828.72647835245),
        ),
    ]
