# Generated by Django 4.0.4 on 2022-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0021_alter_reduceddatum_mjd'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduceddatum',
            name='value_unit',
            field=models.CharField(choices=[('MAG', 'mag'), ('MILLIJANSKY', 'mJy'), ('ERG_S_CM2_ANGSTROM', 'erg/s/cm^2/Angstrom')], default='MAG', max_length=100),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='mjd',
            field=models.FloatField(default=59829.588514701805),
        ),
    ]
