# Generated by Django 4.0.4 on 2022-09-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0022_reduceddatum_value_unit_alter_reduceddatum_mjd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='mjd',
            field=models.FloatField(),
        ),
    ]
