# Generated by Django 4.0.4 on 2022-09-15 11:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0023_alter_targetname_source_name'),
        ('bhtom_dataproducts', '0023_alter_reduceddatum_mjd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reduceddatum',
            options={'get_latest_by': ('mjd',)},
        ),
        migrations.AlterUniqueTogether(
            name='reduceddatum',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='error_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='value_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='wavelengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='error',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='value',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reduceddatum',
            unique_together={('target', 'data_type', 'mjd', 'value', 'value_list', 'filter', 'wavelengths')},
        ),
    ]
