# Generated by Django 4.2.17 on 2025-01-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_alerts', '0007_alter_alertstreammessage_message_id'),
        ('tom_dataproducts', '0012_alter_reduceddatum_data_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='message',
            field=models.ManyToManyField(blank=True, to='tom_alerts.alertstreammessage'),
        ),
    ]
